angular.module('app').constant("apiUrl",{

"autocompleteMedicines":"http://www.healthos.co/api/v1/autocomplete/medicines/brands/{{medicine_query}}",
"autocompleteGenerics":"http://www.healthos.co/api/v1/autocomplete/medicines/generics/{{generic_query}}",
"autocompleteFoodItem":"http://www.healthos.co/api/v1/autocomplete/food/items/{{food_item_query}}",
"searchMedicines":"http://www.healthos.co/api/v1/search/medicines/brands/{{medicine_query}}",
"allMedicines":"http://www.healthos.co/api/v1/medicines/brands?page=1&size=10",
"getMedicine":"http://www.healthos.co/api/v1/medicines/brands/{{medicine_id}}",
"alternativeMedicines":"http://www.healthos.co/api/v1/medicines/brands/{{medicine_id}}/alternatives?page=1&size=10",
"similarMedicines":"http://www.healthos.co/api/v1/medicines/brands/{{medicine_id}}/similar",
"popularUsage":"http://www.healthos.co/api/v1/medicines/brands/{{medicine_id}}/usages",
"commonSideEffects":"http://www.healthos.co/api/v1/medicines/brands/{{medicine_id}}/side_effects",
"searchManufacturers":"http://www.healthos.co/api/v1/search/medicines/manufacturers/{{manufacturer_query}}",
"allManufacturers":"http://www.healthos.co/api/v1/medicines/manufacturers?page=1&size=10",
"allLabTest":"http://www.healthos.co/api/v1/lab_tests?page=1&size=10",
"searchLabTests":"http://www.healthos.co/api/v1/search/lab_tests/{{lab_test_query}}",
"labTest":"http://www.healthos.co/api/v1/lab_tests/{{lab_test_id}}",
"allExcercises":"http://www.healthos.co/api/v1/exercises?page=1&size=10",
"searchExcercises":"http://www.healthos.co/api/v1/search/exercises/{{exercise_query}}",
"Excercise":"http://www.healthos.co/api/v1/exercises/{{exercise_id}}",
"autoCompleteExcercise":"http://www.healthos.co/api/v1/search/exercises/{{exercise_query}}",
"allGenerics":"http://www.healthos.co/api/v1/medicines/generics?page=1&size=10",
"searchGenerics":"http://www.healthos.co/api/v1/search/medicines/generics/{{generic_query}}",
"Generics":"http://www.healthos.co/api/v1/medicines/generics/{{generic_id}}",
"autoCompleteGenerics":"http://www.healthos.co/api/v1/search/medicines/generics/{{generic_query}}",
"autoCompleteLabTest":"http://www.healthos.co/api/v1/autocomplete/lab_tests/{{lab_test_query}}",
"authTokenUrl":"http://www.healthos.co/api/v1/oauth/token.json",
"searchDiseases":"http://www.healthos.co/api/v1/search/diseases/{{disease_query}}",
"autocompleteDiseases":"http://www.healthos.co/api/v1/autocomplete/diseases/{{disease_query}}",
"allDiseases":"http://www.healthos.co/api/v1/diseases?page=1&size=10",
"medicineInteractions":"http://www.healthos.co/api/v1/interactions/medicines/{{medicine_id}}",
"authCredentials":{
        "grant_type": "client_credentials",
        "client_id": "ba040b226a07a25eda30d1c38c20ffa2f90a8e9ab5f60dedd7372c58799f5657",
        "client_secret": "8b3eb395f5dd71896316ac24a5638dee6a72a7e13a11a2f7952c1f9e55b941a8",
        "scope": "public read write"
      },
 "navmenu":{ "menu-item": "Medicines", "submenu":[ "Search Medicines", "All Medicines", "Medicine",  "Common Side Effects", "Search Manufacturers", "All Manufacturers", "Manufacturer", 
  "Medicines by Manufacturer" ] }  
});
